### ISSUE TITLE
Ejemplo de Nuevo Issue

### ISSUE THREAD

**Issue by brian101016** [CaroLina57/git-act-final#4]
Ya revisé su repositorio y debo decir que está todo muy bien hecho.

Me comentaron que trabajaron en equipo ustedes dos, y con este mensaje les confirmo que ya están acreditadas :)

Aprovecharé el Issue para recomendar una modificación al archivo `multydividir.txt` que tiene un error en la línea 2 (dentro de la rama principal), les recomiendo que le pongan

> `(1/0) = ya no da error`

**Comment by CaroLina57** [comment]
Gracias
